import type { SdApi } from "../sdapi";
import type { GenerateOptions, ImageBackend, ImageRequest } from "./types";

/**
 * The sd-api image backend.
 *
 * A pass-through: this is the request shape stages used to build inline, so
 * the mapping is mechanical and the generated bytes are identical to what the
 * pre-adapter code produced. That is the point — the refactor that introduced
 * these interfaces must not change what sd-api renders.
 */
export function sdApiImageBackend(
  sdApi: SdApi,
  provider: { name: string; model: string; defaultParams: Record<string, unknown> },
): ImageBackend {
  return {
    label: provider.name,

    referenceCapacity() {
      // sd-api takes an arbitrary-length `ref_images` array; the practical
      // ceiling is the model's, not the protocol's (finding F16 on the second
      // reference being weaker), and it is not expressed as a number anywhere.
      return Number.POSITIVE_INFINITY;
    },

    async generate(request: ImageRequest, options: GenerateOptions = {}): Promise<Buffer> {
      const payload = {
        prompt: request.prompt,
        ...(request.negativePrompt ? { negative_prompt: request.negativePrompt } : {}),
        model: provider.model,
        width: request.width,
        height: request.height,
        ...(request.seed !== undefined ? { seed: request.seed } : {}),
        ...(provider.defaultParams as Record<string, never>),
        ...(request.references.length > 0
          ? {
              ref_images: request.references,
              // Distinct reference slots, so two people in one frame stay two
              // people. Harmless with a single reference.
              ...(request.references.length > 1 ? { increase_ref_index: true } : {}),
            }
          : {}),
      };

      // Note the spread order above: `defaultParams` overrides the request's
      // own width/height/seed, which is surprising often enough to be worth
      // reporting the merged result rather than making anyone re-derive it.
      options.onResolved?.({ payload });

      return sdApi.image.generate(payload, {
        ...(options.onProgress ? { onProgress: options.onProgress } : {}),
        ...(options.shouldAbort ? { shouldAbort: options.shouldAbort } : {}),
      });
    },

    async uploadReference(bytes: Buffer, filename: string): Promise<string> {
      return sdApi.image.uploadInput(bytes, filename);
    },

    async hasReference(name: string): Promise<boolean> {
      return sdApi.image.hasInput(name);
    },
  };
}
